apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: grafana-admin-password
  namespace: monitoring

spec:
  provider: aws
  parameters:
    region: ca-central-1
    usePodIdentity: "true"
    objects: |
      - objectName: "dev/monitoring/grafana/admin-password"
        objectType: "secretsmanager"
        objectAlias: "grafana-admin-password"
        filePermission: "0440"
