apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: alertmanager-zoho-smtp
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider: aws

  parameters:
    region: ca-central-1
    usePodIdentity: "true"

    objects: |
      - objectName: "dev/monitoring/alertmanager/zoho-smtp-password"
        objectType: "secretsmanager"
        objectAlias: "zoho-smtp-password"
        filePermission: "0440"
