apiVersion: v1
kind: Service
metadata:
  name: gitopsdemo-service
spec:
  selector:
    app.kubernetes.io/name: gitopsdemo
  ports:
  - name: gitopsdemo
    protocol: TCP
    port: 80
    targetPort: http-web-svc