apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
  labels:
    app.kubernetes.io/name: gitopsdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: gitopsdemo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitopsdemo
    spec:
      serviceAccountName: gitopsdemo-serviceaccount
      containers:
        - name: gitopsdemo
          image: conyeukwu25/gitops-demo:ba31fb8
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
