apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
  labels:
    app.kubernetes.io/name: gitopsdemo

spec:
  replicas: 3

  selector:
    matchLabels:
      app.kubernetes.io/name: gitopsdemo

  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitopsdemo

    spec:
      containers:
      - name: gitopsdemo
        image: conyeukwu25/gitops-demo:25540ff
        imagePullPolicy: IfNotPresent

        ports:
        - name: http
          containerPort: 80
          protocol: TCP

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits: 
            cpu: 500m
            memory: 256Mi
        