- name: Install Argo CD on EKS
  hosts: local
  gather_facts: false

  vars:
    ansible_python_interpreter: "{{ playbook_dir }}/../.venv/bin/python"

  pre_tasks:
    - name: Install Python libraries required by Kubernetes modules
      ansible.builtin.pip:
        name:
          - "kubernetes>=24.2.0"
          - PyYAML
          - jsonpatch
        executable: "{{ playbook_dir }}/../.venv/bin/pip"

  roles:
    - argocd
