- name: Install Argo CD on EKS
  hosts: local
  gather_facts: false

  vars:
    aws_profile: dev-admin
    aws_region: ca-central-1
    eks_cluster_name: retail-dev-eksjalexsol
    argocd_namespace: argocd
    argocd_version: v3.4.8

  roles:
    - argocd
