name: Build, Scan and Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - k8s/deployment.yaml

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Validate python syntax
        run: python -m py_compile app.py

      - name: Login to docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Create short Git SHA
        id: vars
        shell: bash
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push multi-architecture image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: conyeukwu25/gitops-demo:${{ steps.vars.outputs.short_sha }}

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: conyeukwu25/gitops-demo:${{ steps.vars.outputs.short_sha }}
          format: table
          vuln-type: os,library
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: "1"

      - name: Update Kubernetes Image tags
        shell: bash
        run: |
          sed -i "s|image: conyeukwu25/gitops-demo:.*|image: conyeukwu25/gitops-demo:${{ steps.vars.outputs.short_sha }}|" k8s/deployment.yaml

      - name: Commit updated deployment
        shell: bash
        run: |
          if git diff --quiet -- k8s/deployment.yaml; then
            echo "Deployment already contains the correct image tag."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m"Update image to ${{ steps.vars.outputs.short_sha }} [skip ci]"
          git push

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout updated deployment
        uses: actions/checkout@v7
        with:
          ref: main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: ca-central-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Connect to EKS cluster
        run: |
          aws eks update-kubeconfig \
            --region ca-central-1 \
            --name retail-dev-eksjalexsol

      - name: Verify kuberbetes access
        run: |
          kubectl auth can-i create deployments --namespace default
          kubectl get pods --namespace default

      - name: Deploy application
        run: |
          kubectl apply -f k8s/

      - name: Wait for deployment
        run: |
          kubectl rollout status deployment/gitops-demo \
            --namespace default \
            --timeout=180s

      - name: Display application resources
        run: |
          kubectl get pods,services \
            --namespace default
